version: '3'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - SESSION_SECRET=your_session_secret_here
    volumes:
      - uploads:/app/uploads

volumes:
  uploads: